# Generated by Django 4.2 on 2023-04-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_item_department_item_frame_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='manufacture_date',
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='製造日'),
        ),
    ]
