# Generated by Django 4.2 on 2023-04-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_item_manufacture_date_alter_item_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='frame_code',
            field=models.CharField(max_length=255, verbose_name='フレーム'),
        ),
        migrations.AlterField(
            model_name='item',
            name='frame_height_fix_side',
            field=models.IntegerField(blank=True, null=True, verbose_name='フレーム高さ固定側'),
        ),
        migrations.AlterField(
            model_name='item',
            name='frame_height_moving_side',
            field=models.IntegerField(blank=True, null=True, verbose_name='フレーム高さ移動側'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_drawing',
            field=models.IntegerField(choices=[(0, 'いいえ'), (1, 'はい')], default=1, verbose_name='製品図面'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_not_our_molds',
            field=models.IntegerField(choices=[(0, 'いいえ'), (1, 'はい')], default=1, verbose_name='他社金型'),
        ),
        migrations.AlterField(
            model_name='item',
            name='molding_machine',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='成型機'),
        ),
        migrations.AlterField(
            model_name='item',
            name='molds_code',
            field=models.CharField(max_length=255, verbose_name='中型'),
        ),
        migrations.AlterField(
            model_name='item',
            name='number_of',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='取数'),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='目付'),
        ),
    ]
