# Generated by Django 4.2 on 2023-04-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_item_is_drawing_alter_item_is_not_our_molds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_drawing',
            field=models.IntegerField(blank=True, choices=[(1, 'はい')], default=0, null=True, verbose_name='製品図面'),
        ),
    ]
