# Generated by Django 4.2 on 2023-04-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_item_is_drawing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_drawing',
            field=models.BooleanField(choices=[(1, 'はい')], default=True, verbose_name='製品図面'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_not_our_molds',
            field=models.BooleanField(choices=[(1, 'はい')], default=True, verbose_name='他社金型'),
        ),
    ]
