# Generated by Django 4.2 on 2023-04-14 04:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_item_is_drawing_alter_item_is_not_our_molds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='molds_code',
            new_name='mold_code',
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(verbose_name='製造日'),
        ),
        migrations.AlterField(
            model_name='item',
            name='department',
            field=models.CharField(choices=[('道北', '道北'), ('道東', '道東'), ('道央', '道央'), ('道南', '道南'), ('小樽', '小樽'), ('青森', '青森'), ('宮城', '宮城'), ('宮城第二', '宮城第二'), ('関東', '関東'), ('銚子', '銚子'), ('東京', '東京'), ('神奈川', '神奈川'), ('新潟', '新潟'), ('北陸', '北陸'), ('沼津', '沼津'), ('焼津', '焼津'), ('本部', '本部'), ('名古屋', '名古屋'), ('三重', '三重'), ('中部', '中部'), ('大阪', '大阪'), ('四国', '四国'), ('広島', '広島'), ('福岡', '福岡'), ('長崎', '長崎'), ('鹿児島', '鹿児島')], default='沼津', max_length=255, verbose_name='管理籍'),
        ),
        migrations.AlterField(
            model_name='item',
            name='frame_code',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9_@\\-\\.]+$')], verbose_name='フレーム'),
        ),
    ]
