# Generated by Django 4.2 on 2023-05-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_item_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temp',
            options={},
        ),
        migrations.RemoveField(
            model_name='item',
            name='age',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sex',
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='製品名'),
        ),
    ]
