# Generated by Django 4.2 on 2023-05-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_item_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='manufacture_date',
            field=models.DateField(blank=True, null=True, verbose_name='製造年月'),
        ),
    ]
