# Generated by Django 4.2 on 2023-05-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_item_manufacture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='inner_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='V'),
        ),
        migrations.AddField(
            model_name='item',
            name='inner_length',
            field=models.IntegerField(blank=True, null=True, verbose_name='T'),
        ),
        migrations.AddField(
            model_name='item',
            name='inner_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='U'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_lid',
            field=models.BooleanField(default=True, verbose_name='AF'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_with_lid',
            field=models.BooleanField(default=True, verbose_name='AG'),
        ),
        migrations.AddField(
            model_name='item',
            name='outer_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='S'),
        ),
        migrations.AddField(
            model_name='item',
            name='outer_length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Q'),
        ),
        migrations.AddField(
            model_name='item',
            name='outer_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='R'),
        ),
    ]
