# Generated by Django 4.2 on 2023-05-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_item_inner_height_item_inner_length_item_inner_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='usage_notes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='用途'),
        ),
        migrations.AlterField(
            model_name='item',
            name='inner_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='内寸 深さ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='inner_length',
            field=models.IntegerField(blank=True, null=True, verbose_name='内寸 長さ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='inner_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='内寸 幅'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_lid',
            field=models.BooleanField(default=True, verbose_name='蓋'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_with_lid',
            field=models.BooleanField(default=True, verbose_name='蓋付'),
        ),
        migrations.AlterField(
            model_name='item',
            name='outer_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='外寸 高さ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='outer_length',
            field=models.IntegerField(blank=True, null=True, verbose_name='外寸 長さ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='outer_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='外寸 幅'),
        ),
    ]
